### ISSUE TITLE
Hyperlink

### ISSUE THREAD

**Issue by drfurtado** [shafayetShafee/bsicons#1]
I want to display the icon and make it clickable so that it points to a page - is it possible?

Thank you!

**Comment by shafayetShafee** [comment]
I am currently suffering from recurrent high fever. I will get to this as soon as possible. Thank you for your patience 🙂.

**Comment by shafayetShafee** [comment]
Yes It is possible. You just need to wrap the shortcode inside the `<a>` tag.

A quick example,

~~~
---
title: "bsicons as link"
format: revealjs
---

## Quarto

Quarto enables you to weave together content and executable code into a finished 
presentation. see  <a href="#/code">{{< bi code-slash >}}</a>


## Code

When you click the **Render** button a presentation will be generated that includes 
both content and the output of embedded code. You can embed code like this:

```{r}
#| echo: true

1 + 1
```
~~~
